### ISSUE TITLE
Installation script for Fedora Linux

### ISSUE THREAD

**Issue by leonjia0112** [keylime/python-keylime#31]
# Description 
An installation script for Fedora would be quite helpful for the new version of Keylime.

Now there is only installation script and instruction for both Centos and Ubuntu Linux. Due to the difference of repository management between Fedora and Centos. If there is a manual installation instruction that would be greatly helpful.

You can assign this to me if you haven't started working on this feature.

Another thing, since Fedora 29 has already migrated everything to python 3, which is quite different than 28. I think an additional step for Fedora 29 is needed.

**Comment by lukehinds** [comment]
@leonjia0112 there is an [ansible role](https://github.com/keylime/ansible-keylime) now that deploys Python Keylime and the Rust cloud node on Fedora 28 (although its due an update since the TPM 2.0 code landed and Fedora 29). I also opened https://github.com/keylime/python-keylime/issues/32 to track python 3 support.

I have some Dockerfiles inbound which will deploy and set up Keylime in CI.

In regards to the bash installer it definitely needs an update, but I wonder what direction we should take with this going forward.... 

Keylime can be deployed in multiple ways, from an all in one host / "test drive it" form, to ultimately an architecture in the form of multiple nodes for each component (cloud node, registrar , verifier etc)  with an increasing amount of specific component set ups (openssl / cfssl & tpm 1.2 / 2.0) etc. I am mindful that if we provide an installer script covering all dists and deployment modes, it's going to become quite a complex and challenging to maintain. This sort of installer would be better suited to a deployment tool such as ansible / puppet etc, that can make use of existing community modules and abstract away having to handle things such as config variables, target hosts etc.

So with the previous paragraph in mind, I would say update the installer if its initially useful to you, but going forward we should consider if we want to frame the bash installer as the go to approach to deploying keylime. 

Hope that makes sense, happy to chat this out here to find an approach we all find best suited.

**Comment by jetwhiz** [comment]
@lukehinds I definitely agree with using something more akin to ansible / puppet to make installation of specific parts of Keylime (as needed) more user-friendly and powerful/flexible than a bash script. 

The bash script could be useful in the meantime though to quickly get a full environment up and running on one machine.  If I remember correctly, the latest version of the [installer.sh](https://github.com/keylime/python-keylime/blob/master/installer.sh) script should already support Fedora 29, since we're explicitly installing python2 (though as you mentioned, porting Keylime to python3 is still a work in progress).

**Comment by lukehinds** [comment]
ack, makes sense @jetwhiz 

assigning to you @leonjia0112

**Comment by lukehinds** [comment]
Going to close this for now, as we do support Fed 29 since @jetwhiz pushed the tpm 2.0 code.
