### ISSUE TITLE
Socket mode installation flag confusion

### ISSUE THREAD

**Issue by leonjia0112** [keylime/python-keylime#61]
# Description 
In the installation, there is an option as following
`-s              Install TPM in socket/simulator mode (vs. chardev)`
Does it mean that the TPM would only use chardev for socket mode or
chardev for 1.2 chosen and ibm simulator for 2.0 chosen. It makes more
sense if it is the latter meaning, but I am not so sure.

Thanks.

**Comment by nabilschear** [comment]
we should clear this up.  @jetwhiz i believe that -s will cause tpm2 to use swtpm2 as well.  So, i think the latter explanation is correct.

this is the mode that will make keylime talk to a software emulator.  the socket/chardev stuff is all a relic of how tpm4720 does thing.  now with tpm2, this is all muddled.

**Comment by jetwhiz** [comment]
The `-s` (simulator mode) and `-m` (modern TPM2) options are independent of each other from a high-level perspective.  Simulator mode will use a simulated/emulated TPM (either 1.2 or 2.0, depending on the `-m` choice), otherwise it will expect to be communicating with a real TPM (as a character device).  

So there are four possible combinations: 
1. `./installer.sh -sm` : Install Keylime using a simulated TPM 2.0 (swtpm2 emulator)
2. `./installer.sh -s` : Install Keylime using a simulated TPM 1.2 (tpm4720 emulator)
3. `./installer.sh -m` : Install Keylime using a real/non-emulator TPM 2.0 (chardev)
4. `./installer.sh` : Install Keylime using a real/non-emulator TPM 1.2 (chardev)

So if you do not have a TPM built into your machine and you want to use the TPM 2.0 protocol, then you would have to install Keylime with `./installer.sh -sm`, which will install the swtpm2 emulator for you. 

Note that Keylime always expects that a resource manager is being used for TPM2, since it is *not* recommended to communicate directly with the TPM2.  This means that if you do not want to install the tpm2-abrmd resource manager for some strange reason, you will need to override the TPM2TOOLS_TCTI environment variable as described here: https://github.com/keylime/python-keylime#tpm-20-resource-manager

> Alternatively, it is also possible, though not recommended, to communicate directly with the TPM (and not use a resource manager). This can be done by setting the environment var TPM2TOOLS_TCTI to the appropriate value:
> 
> For swtpm2 emulators: export TPM2TOOLS_TCTI="mssim:port=2321"
> 
> For chardev communication: export TPM2TOOLS_TCTI="device:/dev/tpm0"

**Comment by lukehinds** [comment]
closing this for now, from the comprehensive answer from @jetwhiz
