### ISSUE TITLE
enable tpm4720 in socket mode

### ISSUE THREAD

**Issue by leonjia0112** [keylime/python-keylime#72]
# Description 
In the `./install.sh` [line 480](https://github.com/keylime/python-keylime/blob/master/installer.sh#L480), it said `# Start tpm4720`. Just a little confused, if I chose TPM2 to install Keylime, would this service target on TPM1.2/2.0 accordingly or only for TPM1.2 (TPM4720).

Because I am working on RPM package for Fedora29 w/ TPM2/simulator, wondering whether it is necessary to put this service into the rpm packaging step.

Thanks!

**Comment by lukehinds** [comment]
Hi Leo, so you plan to also  package the simulator alongside keylime? I think it might be better donr separately. Ultimately we want folks to use keylime in production with a hardware TPM.

**Comment by leonjia0112** [comment]
Hi @lukehinds , that is a good point. The plan is to package python-keylime without the simulator ideally. But I think for testing, I would like to try to package python-keylime for a Fedora platform with TPM2 and tpm2 simulator on it. By using the package, folks should be able to install python-keylime just using the `setup.py` instead of using `installer.sh`. This is what I am thinking.

**Comment by lukehinds** [comment]
Understand, I think a simple resolution would be to package the simulator on its own. The reason I say this is because Fedora prefer to package python RPMS separately. 

On a separate note, thinking about this we should also do Package dependencies to tpm2-tss, tpm2-abrmd and tools when the EAPI issues are fixed. We could do this as a topic next week in the first meeting.

**Comment by leonjia0112** [comment]
Sure! This is exactly what I am trying to achieve. We can definitely discuss this next week as a topic. :+1:

**Comment by lukehinds** [comment]
Can we close now @leonjia0112 ?
